name: C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake
        run: sudo apt install -y cmake
      - name: install dependencies
        run: sudo apt install -y libeigen3-dev libspdlog-dev
      - name: configure
        run: ./configure && ./configure
      - name: make
        run: make
        working-directory: build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake and googletest
        run: sudo apt install -y cmake libgmock-dev lcov libeigen3-dev libspdlog-dev
      - name: configure
        run: ./configure && CMAKE_OPTIONS="-DOPTION_ENABLE_COVERAGE=On" ./configure
      - name: tests
        run: make test
        working-directory: build
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake
        run: sudo apt install -y cmake cppcheck clang-tidy
      - name: configure
        run: ./configure && ./configure
      - name: check
        run: make check-all
        working-directory: build
